<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    public function run()
    {
        $categories = [
            "Vegetables",
            "Fruits",
            "Electronics",
            "Clothing",
            "Books",
            "Home & Garden",
            "Toys",
            "Sports",
            "Beauty & Personal Care",
            "Health & Wellness",
            "Jewelry",
            "Automotive",
            "Music",
            "Movies",
            "Pets",
            "Food & Beverages",
            "Shoes",
            "Furniture",
            "Accessories",
            "Art & Crafts",
            "Stationery",
            "Outdoor",
            "Tools",
            "Computers",
            "Gaming",
            "Travel",
            "Baby",
            "Watches",
            "Collectibles",
            "Industrial",
            "Fitness",
            "Party Supplies",
            "Pet Supplies",
            "Vintage",
            "Antiques",
            "Handmade",
            "Hobbies",
            "Kitchen",
            "Office",
            "School Supplies",
            "Medical Supplies",
            "Home Improvement",
            "Gardening",
            "Baking",
            "Camping",
            "Photography",
            "Music Instruments",
            "Cookware",
            "Dining",
            "Bathroom",
            "Bedroom",
            "Living Room",
            "Patio",
            "Tools",
            "Electrical",
            "Plumbing",
            "Healthcare",
            "Beauty Products",
            "Cosmetics",
            "Perfume",
            "Wine",
            "Spirits",
            "Beer",
            "Coffee",
            "Tea",
            "Soft Drinks",
            "Snacks",
            "Chocolates",
            "Candies",
            "Cookies",
            "Desserts",
            "Frozen Foods",
            "Organic",
            "Gluten-Free",
            "Vegan",
            "Vegetarian",
            "Meat",
            "Poultry",
            "Seafood",
            "Dairy",
            "Eggs",
            "Bakery",
            "Breakfast",
            "Cereal",
            "Pasta",
            "Rice",
            "Sauces",
            "Spices",
            "Canned Foods",
            "Soups",
            "Condiments",
            "Snack Foods",
            "Chips",
            "Nuts",
            "Dried Fruits",
            "Trail Mix",
            "Salsa",
            "Popcorn",
            "Gourmet Foods",
            "Oils",
            "Vinegars",
            "Organic Foods",
            "Superfoods",
            "Specialty Diets",
            "Gluten-Free Foods",
            "Paleo Diet",
            "Keto Diet",
            "Mediterranean Diet",
            "DASH Diet",
            "Vegetarian Foods",
            "Vegan Foods",
            "Low-Carb Foods",
            "Protein Bars",
            "Supplements",
            "Vitamins",
            "Minerals",
            "Herbal Supplements",
            "Protein Powders",
            "Meal Replacement Shakes",
            "Energy Drinks",
            "Tea",
            "Coffee",
            "Detox Products",
            "Weight Loss",
            "Hair Care",
            "Skincare",
            "Makeup",
            "Nail Care",
            "Fragrances",
            "Men's Grooming",
            "Bath & Body",
            "Shaving",
            "Hair Removal",
            "Cosmetic Bags",
            "Wigs",
            "Extensions",
            "Hair Accessories",
            "Hair Color",
            "Styling Products",
            "Hair Tools",
            "Body Wash",
            "Lotions",
            "Deodorants",
            "Sunscreen",
            "Tanning",
            "Tattoos",
            "Piercings",
            "Oral Care",
            "Dental Care",
            "Shampoos",
            "Conditioners",
            "Hair Masks",
            "Serums",
            "Treatments",
            "Sunscreens",
            "Lip Care",
            "Eye Creams",
            "Anti-Aging",
            "Cleansers",
            "Toners",
            "Masks",
            "Exfoliants",
            "Makeup Removers",
            "Body Scrubs",
            "Hand Sanitizers",
        ];

        foreach ($categories as $category) {
            DB::table("categories")->insert([
                "name" => $category,
            ]);
        }
    }
}
